### PR TITLE
Preliminary Design Review

### PR DESCRIPTION
**Pull request by KenwoodFox**
Merge into `main` when this PDR is submitted to brightspace.

### CODE REVIEW

**Comment by KenwoodFox** [comment]
We still gotta work on this

**Comment by KenwoodFox** [comment]
PDR presentations take place in `room 318`

**Review by MariaTswizz — APPROVED** [review]
Looks good to me

**Comment by KenwoodFox** [comment]
Two review approvals, im merging this in as soon as CI/CD says it checks out! <3

**Pull request merged**
